### PR TITLE
Add possibility to disable token validation

### PR DESCRIPTION
**Pull request by zohmi**

### CODE REVIEW

**Comment by DavidLambauer** [comment]
pog @zohmi <3. 

Do you need a new release? most likely huh

**Comment by zohmi** [comment]
> 

Would be nice, yeah. Thanks a lot :-)

**Comment by DavidLambauer** [comment]
done. Have fun !

David Lambauer +49 176 66 890 102 ( tel:+4917666890102 ) Geschäftsführer / CEO run-as-root.sh ( https://run-as-root.sh/ )

Sent via Superhuman ( ***@***.*** )

**Comment by zohmi** [comment]
Thanks a lot... Would you mind updating the composer.json with the current version? That would be fantastic :-)

**Comment by DavidLambauer** [comment]
Done. Sorry. Always the same stupid stuff. I actually think the version tag is not necessary, isn't it?

**Comment by zohmi** [comment]
No worries. Yes, I also leave it out most often.

**Pull request merged**
